{
 "title": "Pulsar Perf Benchmark (PPFB)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "clnt_type",
    "label": "Client Type",
    "query": "ppfb_thrupt_msg_s{clnt_type=~\".+\"}"
   }
  ]
 },
 "panels": [
  { "title": "Performance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Throughput: Msg/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(ppfb_thrupt_msg_s) by (clnt_type)"
    }
   ]
  },
  {
   "title": "Throughput: Mbit/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(ppfb_thrupt_Mbit_s) by (clnt_type)"
    }
   ]
  },
  {
   "title": "Throughput: Failure Msg/s",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(ppfb_thrupt_failure_msg_s) by (clnt_type)"
    }
   ]
  },
  {
   "title": "Latency Percentile (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(ppfb_latency_med) by (clnt_type)",
     "legendFormat": "Median"
    },
    {
     "expr": "avg(ppfb_latency_95pc) by (clnt_type)",
     "legendFormat": "95%"
    },
    {
     "expr": "avg(ppfb_latency_99pct) by (clnt_type)",
     "legendFormat": "99%"
    }
   ]
  }
 ]
}