- name: Format disks
  filesystem:
    fstype: xfs
    dev: '{{ item }}'
  with_items:
    - "{{ gzk_storage_blk_device }}"

- name: Mount disks
  mount:
    path: "{{ gzk_storage_mnt_path }}"
    src: "{{ gzk_storage_blk_device }}"
    fstype: xfs
    opts: defaults,noatime,nodiscard
    state: mounted

- name: Change bookie directory ownership
  file:
    path: "{{ tgt_pulsar_inst_dir }}/data"
    state: directory
    recurse: yes
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user }}"