[pulsar:children]
cluster_srv
cluster_clnt
global_zk

[cluster_srv:children]
cluster_srv_A
cluster_srv_B

[cluster_srv_A]
18.221.243.57 private_ip=172.16.10.37 cluster_name=ClusterA srv_type=bookie
18.222.107.75 private_ip=172.16.10.169 cluster_name=ClusterA srv_type=broker
3.137.160.46 private_ip=172.16.10.101 cluster_name=ClusterA srv_type=zk

[cluster_srv_B]
3.142.52.103 private_ip=172.16.20.208 cluster_name=ClusterB srv_type=bookie
18.188.22.149 private_ip=172.16.20.111 cluster_name=ClusterB srv_type=broker
3.143.224.78 private_ip=172.16.20.171 cluster_name=ClusterB srv_type=zk

[cluster_clnt]

[global_zk]
18.223.113.65 private_ip=172.16.30.82

