###
# This is used for a Pulsar instance deployment with 2 Clusters: ClusterA and ClusterB
###
---
##
# Get a string for all pulsar borker nodes with web service listening ports, e.g.
#   <broker_node_1>:6550,<broker_node_2>:6550,<broker_node_3>:6550
- name: Get "web-service-url" (IP:Port) list (No DNS)
  set_fact:
    web_service_url_str_clusterATemp: "{% for node in groups['cluster_srv_A'] %}{%if hostvars[node].srv_type=='broker' %}{{ hostvars[node].private_ip }}:{{ web_svc_port }},{% endif %}{% endfor %}"
    web_service_url_str_clusterBTemp: "{% for node in groups['cluster_srv_B'] %}{%if hostvars[node].srv_type=='broker' %}{{ hostvars[node].private_ip }}:{{ web_svc_port }},{% endif %}{% endfor %}"
- name: Remove trailing "," character    
  set_fact:
    web_service_url_str_clusterA: "{{ web_service_url_str_clusterATemp | regex_replace(',$','') }}"     
    web_service_url_str_clusterB: "{{ web_service_url_str_clusterBTemp | regex_replace(',$','') }}"  
- debug: msg="web_service_url_str_clusterA - {{ web_service_url_str_clusterA }}; web_service_url_str_clusterB - {{web_service_url_str_clusterB}}"
  when: show_debug_msg|bool

##
# Get a string for all pulsar borker nodes with web service TLS listening ports, e.g.
#   <broker_node_1>:6551,<broker_node_2>:6551,<broker_node_3>:6551
- name: Get "web-service-url-tls" (IP:Port) list (No DNS)
  set_fact:
    web_service_url_tls_str_clusterATemp: "{% for node in groups['cluster_srv_A'] %}{%if hostvars[node].srv_type=='broker' %}{{ hostvars[node].private_ip }}:{{ web_svc_port_tls }},{% endif %}{% endfor %}"
    web_service_url_tls_str_clusterBTemp: "{% for node in groups['cluster_srv_B'] %}{%if hostvars[node].srv_type=='broker' %}{{ hostvars[node].private_ip }}:{{ web_svc_port_tls }},{% endif %}{% endfor %}"
- name: Remove trailing "," character    
  set_fact:
    web_service_url_tls_str_clusterA: "{{ web_service_url_tls_str_clusterATemp | regex_replace(',$','') }}"     
    web_service_url_tls_str_clusterB: "{{ web_service_url_tls_str_clusterBTemp | regex_replace(',$','') }}"    
- debug: msg="web_service_url_tls_str_clusterA - {{ web_service_url_tls_str_clusterA }}; web_service_url_tls_str_clusterB - {{ web_service_url_tls_str_clusterB }}"
  when: show_debug_msg|bool

##
# Get a string for all pulsar borker nodes with broker service listening ports, e.g.
#   <broker_node_1>:8080,<broker_node_2>:8080,<broker_node_3>:8080
- name: Get "broker-service-url" (IP:Port) list (No DNS)
  set_fact:
    broker_service_url_str_clusterATemp: "{% for node in groups['cluster_srv_A'] %}{%if hostvars[node].srv_type=='broker' %}{{ hostvars[node].private_ip }}:{{ broker_svc_port }},{% endif %}{% endfor %}"
    broker_service_url_str_clusterBTemp: "{% for node in groups['cluster_srv_B'] %}{%if hostvars[node].srv_type=='broker' %}{{ hostvars[node].private_ip }}:{{ broker_svc_port }},{% endif %}{% endfor %}"
- name: Remove trailing "," character    
  set_fact:
    broker_service_url_str_clusterA: "{{ broker_service_url_str_clusterATemp | regex_replace(',$','') }}"     
    broker_service_url_str_clusterB: "{{ broker_service_url_str_clusterBTemp | regex_replace(',$','') }}"      
- debug: msg="broker_service_url_str_clusterA - {{ broker_service_url_str_clusterA }}; broker_service_url_str_clusterB - {{ broker_service_url_str_clusterB }}"
  when: show_debug_msg|bool

##
# Get a string for all pulsar borker nodes with broker service TLS listening ports, e.g.
#   <broker_node_1>:8443,<broker_node_2>:8443,<broker_node_3>:8443
- name: Get "broker-service-url-tls" (IP:Port) list (No DNS)
  set_fact:
    broker_service_url_tls_str_clusterA: "{% for node in groups['cluster_srv_A'] %}{%if hostvars[node].srv_type=='broker' %}{{ hostvars[node].private_ip }}:{{ broker_svc_port_tls }},{% endif %}{% endfor %}"
    broker_service_url_tls_str_clusterB: "{% for node in groups['cluster_srv_B'] %}{%if hostvars[node].srv_type=='broker' %}{{ hostvars[node].private_ip }}:{{ broker_svc_port_tls }},{% endif %}{% endfor %}"
- debug: msg="broker_service_url_tls_str_clusterA - {{ broker_service_url_tls_str_clusterA }}; broker_service_url_tls_str_clusterB - {{ broker_service_url_tls_str_clusterB }}"
  when: show_debug_msg|bool